### ISSUE TITLE
Array dimension mismatch

### ISSUE THREAD

**Issue by bil022** [hubmapconsortium/spatial-transcriptomics-pipeline#50] opened 2024-02-15 01:10 UTC
Hi,

We run the pipefish pipeline. The first error was the package pyro was not found, we built a new docker image with pyro-ppl installed. The error was fixed and now it produced the error at run time in the container:
<img width="684" alt="Screenshot 2024-02-14 at 4 18 22 PM" src="https://github.com/hubmapconsortium/spatial-transcriptomics-pipeline/assets/8838029/4c7f9f6e-f8dd-4d83-a611-98eed18d9044">

I am using your example set(iss_mouse_brain).

Can you help?

Thanks,

**Comment by ctcisar** [comment] 2024-02-15 01:30
Hi,
Could you provide how you invoked the pipeline (ex `cwltool [options] pipeline.cwl /data/pipeline.yml`), and any output prior to this error?

Thanks,
Cecilia

**Comment by bil022** [comment] 2024-02-15 02:40
Hi,

Thanks! I ran:
cwltool --cachedir cache --debug pipeline.cwl iss_mouse_brain/pipeline.yml | tee iss_mouse_brain.log.  I've attached the output.

Thanks,
Bin
________________________________

**Comment by bil022** [comment] 2024-02-16 20:08
Hi,

Any progress/updates?

Thanks!
Bin
________________________________

**Comment by ctcisar** [comment] 2024-02-16 22:25
Hi Bin,
We have replicated the issue and are trying to isolate the cause shortly.
However due to the long weekend, we do not expect to have any answers until
the 21st or 20th at the earliest.

The bug appears to be in the code converting the initial listed coordinates
to the saved coordinates per fov, so you should not face this error if you
use a dataset that does not require postcode decoding.

Best,
Cecilia

**Comment by bil022** [comment] 2024-02-22 00:27
Hi, Cecilia:

Please let me know if the bug is fixed.

Thanks,
Bin
________________________________

**Comment by ctcisar** [comment] 2024-02-22 00:48
I will let you know when an update has been pushed.

**Comment by ctcisar** [comment] 2024-02-22 23:20
Ok, I have tested that this dataset is working again. If you are using a linux or windows machine you can switch to the `:master` branch and re-download the cwl files and verify this.

I am working on getting the Mac build online, after which this patch will be added to `:release`.

**Comment by ctcisar** [comment] 2024-02-29 22:38
This fix has been rolled into v3.1 of [release](https://github.com/hubmapconsortium/spatial-transcriptomics-pipeline/releases/tag/v3.1).

**Closed by ctcisar** 2024-02-29 22:38 UTC
